### ISSUE TITLE
Evaluate Derivative for Specific Input and Output Index

### ISSUE THREAD

**Issue by alegresor** [UM-Bridge/UMBridge.jl#5]
For the [Cantilevered Beam problem](https://um-bridge-benchmarks.readthedocs.io/en/docs/forward-benchmarks/muq-beam-propagation.html) with 3 inputs `x` and 31 outputs `y` I want to evaluate $\partial y[16] / \partial x[2]$ with indexing starting from 1. 

The current `gradient` function is defined as 

```julia 
function gradient(model::HTTPModel, out_wrt, in_wrt, input, sens, config = Dict())
    body = Dict(
        "name" =>name(model),
        "outWrt" => out_wrt,
        "inWrt" => in_wrt,
        "input" => input,
        "sens" => sens,
        "config" => config
    )
```

For $x = [1,1,1]$ I tried 

```julia 
UMBridge.gradient(model, 16, 2, [[1,1,1]], ones(31))
```

but get 

```
{"error":{"message":"Input inWrt out of range! Expected between 0 and 0 but got 2","type":"InvalidInput"}}""")
```

Also, I am unsure what `sens` does. 

Thanks!

**Comment by linusseelinger** [comment]
Hi @alegresor !

First of all: A UM-Bridge model may have multiple input and output vectors. `in_wrt` and `out_wrt` select which input and which output to consider in the following. (That feature can be useful if you want to combine multiple models that feed into each other, and e.g. apply chain rule to them.)
The model you are looking at only has 1 input vector and 1 output vector, so `in_wrt` and `out_wrt` should in fact be 0 here.

`gradient` then gives you $\text{sens}^T J(\text{input})$, where J is the model's Jacobian. So I think you'll want to set $\text{sens} = (0, \ldots, 0, 1, 0, \ldots, 0)^T$. The output of `gradient` should then give you $(\partial y[16] / \partial x[1], \ldots, \partial y[16] / \partial x[3])$, from which you can select the appropriate value.

Let me know if that works! :)

**Comment by alegresor** [comment]
Got it, thanks!
